/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite Runner API
 * BoxLite Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EnumsBackupState } from './enums-backup-state';
// May contain unused imports in some cases
// @ts-ignore
import type { EnumsBoxState } from './enums-box-state';

export interface BoxInfoResponse {
    'backupError'?: string;
    'backupSnapshot'?: string;
    'backupState'?: EnumsBackupState;
    'daemonVersion'?: string;
    'state'?: EnumsBoxState;
}



