/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite Runner API
 * BoxLite Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const EnumsBoxState = {
    BoxStateCreating: 'creating',
    BoxStateRestoring: 'restoring',
    BoxStateDestroyed: 'destroyed',
    BoxStateDestroying: 'destroying',
    BoxStateStarted: 'started',
    BoxStateStopped: 'stopped',
    BoxStateStarting: 'starting',
    BoxStateStopping: 'stopping',
    BoxStateResizing: 'resizing',
    BoxStateError: 'error',
    BoxStateUnknown: 'unknown',
    BoxStatePullingSnapshot: 'pulling_snapshot',
} as const;

export type EnumsBoxState = typeof EnumsBoxState[keyof typeof EnumsBoxState];



