/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface OidcConfig {
    /**
     * OIDC issuer
     */
    'issuer': string;
    /**
     * OIDC client ID
     */
    'clientId': string;
    /**
     * OIDC audience
     */
    'audience': string;
    /**
     * OIDC end-session endpoint. Set when the IdP does not advertise one via discovery (e.g. Dex) and BoxLite hosts a compatible logout endpoint.
     */
    'endSessionEndpoint'?: string;
}

