/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateOrganizationQuota {
    'maxCpuPerBox': number | null;
    'maxMemoryPerBox': number | null;
    'maxDiskPerBox': number | null;
    'snapshotQuota': number | null;
    'maxSnapshotSize': number | null;
    'volumeQuota': number | null;
    'authenticatedRateLimit': number | null;
    'boxCreateRateLimit': number | null;
    'boxLifecycleRateLimit': number | null;
    'authenticatedRateLimitTtlSeconds': number | null;
    'boxCreateRateLimitTtlSeconds': number | null;
    'boxLifecycleRateLimitTtlSeconds': number | null;
    /**
     * Time in minutes before an unused snapshot is deactivated
     */
    'snapshotDeactivationTimeoutMinutes': number | null;
}

