/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BoxDesiredState } from './box-desired-state';
// May contain unused imports in some cases
// @ts-ignore
import type { BoxInfo } from './box-info';
// May contain unused imports in some cases
// @ts-ignore
import type { BoxState } from './box-state';
// May contain unused imports in some cases
// @ts-ignore
import type { BoxVolume } from './box-volume';
// May contain unused imports in some cases
// @ts-ignore
import type { BuildInfo } from './build-info';

export interface Workspace {
    /**
     * The ID of the sandbox
     */
    'id': string;
    /**
     * The organization ID of the sandbox
     */
    'organizationId': string;
    /**
     * The name of the sandbox
     */
    'name': string;
    /**
     * The snapshot used for the sandbox
     */
    'snapshot'?: string;
    /**
     * The user associated with the project
     */
    'user': string;
    /**
     * Environment variables for the sandbox
     */
    'env': { [key: string]: string; };
    /**
     * Labels for the sandbox
     */
    'labels': { [key: string]: string; };
    /**
     * Whether the box http preview is public
     */
    'public': boolean;
    /**
     * Whether to block all network access for the sandbox
     */
    'networkBlockAll': boolean;
    /**
     * Comma-separated list of allowed CIDR network addresses for the sandbox
     */
    'networkAllowList'?: string;
    /**
     * The target environment for the sandbox
     */
    'target': string;
    /**
     * The CPU quota for the sandbox
     */
    'cpu': number;
    /**
     * The GPU quota for the sandbox
     */
    'gpu': number;
    /**
     * The memory quota for the sandbox
     */
    'memory': number;
    /**
     * The disk quota for the sandbox
     */
    'disk': number;
    /**
     * The state of the sandbox
     */
    'state'?: BoxState;
    /**
     * The desired state of the sandbox
     */
    'desiredState'?: BoxDesiredState;
    /**
     * The error reason of the sandbox
     */
    'errorReason'?: string;
    /**
     * Whether the box error is recoverable.
     */
    'recoverable'?: boolean;
    /**
     * The state of the backup
     */
    'backupState'?: WorkspaceBackupStateEnum;
    /**
     * The creation timestamp of the last backup
     */
    'backupCreatedAt'?: string;
    /**
     * Auto-stop interval in minutes (0 means disabled)
     */
    'autoStopInterval'?: number;
    /**
     * Auto-archive interval in minutes
     */
    'autoArchiveInterval'?: number;
    /**
     * Auto-delete interval in minutes (negative value means disabled, 0 means delete immediately upon stopping)
     */
    'autoDeleteInterval'?: number;
    /**
     * Array of volumes attached to the sandbox
     */
    'volumes'?: Array<BoxVolume>;
    /**
     * Build information for the sandbox
     */
    'buildInfo'?: BuildInfo;
    /**
     * The creation timestamp of the sandbox
     */
    'createdAt'?: string;
    /**
     * The last update timestamp of the sandbox
     */
    'updatedAt'?: string;
    /**
     * The class of the sandbox
     * @deprecated
     */
    'class'?: WorkspaceClassEnum;
    /**
     * The version of the daemon running in the sandbox
     */
    'daemonVersion'?: string;
    /**
     * The runner ID of the sandbox
     */
    'runnerId'?: string;
    /**
     * The toolbox proxy URL for the sandbox
     */
    'toolboxProxyUrl': string;
    /**
     * The image used for the workspace
     */
    'image'?: string;
    /**
     * The state of the snapshot
     */
    'snapshotState'?: WorkspaceSnapshotStateEnum;
    /**
     * The creation timestamp of the last snapshot
     */
    'snapshotCreatedAt'?: string;
    /**
     * Additional information about the sandbox
     */
    'info'?: BoxInfo;
}

export const WorkspaceBackupStateEnum = {
    NONE: 'None',
    PENDING: 'Pending',
    IN_PROGRESS: 'InProgress',
    COMPLETED: 'Completed',
    ERROR: 'Error',
} as const;

export type WorkspaceBackupStateEnum = typeof WorkspaceBackupStateEnum[keyof typeof WorkspaceBackupStateEnum];
export const WorkspaceClassEnum = {
    SMALL: 'small',
    MEDIUM: 'medium',
    LARGE: 'large',
} as const;

export type WorkspaceClassEnum = typeof WorkspaceClassEnum[keyof typeof WorkspaceClassEnum];
export const WorkspaceSnapshotStateEnum = {
    NONE: 'None',
    PENDING: 'Pending',
    IN_PROGRESS: 'InProgress',
    COMPLETED: 'Completed',
    ERROR: 'Error',
} as const;

export type WorkspaceSnapshotStateEnum = typeof WorkspaceSnapshotStateEnum[keyof typeof WorkspaceSnapshotStateEnum];


