/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite Runner API
 * BoxLite Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * BoxliteApi - axios parameter creator
 */
export const BoxliteApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Attach to an execution via WebSocket
         * @param {string} boxId Box ID
         * @param {string} execId Execution ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1BoxesBoxIdExecutionsExecIdAttachGet: async (boxId: string, execId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'boxId' is not null or undefined
            assertParamExists('v1BoxesBoxIdExecutionsExecIdAttachGet', 'boxId', boxId)
            // verify required parameter 'execId' is not null or undefined
            assertParamExists('v1BoxesBoxIdExecutionsExecIdAttachGet', 'execId', execId)
            const localVarPath = `/v1/boxes/{boxId}/executions/{execId}/attach`
                .replace('{boxId}', encodeURIComponent(String(boxId)))
                .replace('{execId}', encodeURIComponent(String(execId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BoxliteApi - functional programming interface
 */
export const BoxliteApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BoxliteApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Attach to an execution via WebSocket
         * @param {string} boxId Box ID
         * @param {string} execId Execution ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1BoxesBoxIdExecutionsExecIdAttachGet(boxId: string, execId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1BoxesBoxIdExecutionsExecIdAttachGet(boxId, execId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BoxliteApi.v1BoxesBoxIdExecutionsExecIdAttachGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BoxliteApi - factory interface
 */
export const BoxliteApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BoxliteApiFp(configuration)
    return {
        /**
         * 
         * @summary Attach to an execution via WebSocket
         * @param {string} boxId Box ID
         * @param {string} execId Execution ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1BoxesBoxIdExecutionsExecIdAttachGet(boxId: string, execId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1BoxesBoxIdExecutionsExecIdAttachGet(boxId, execId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BoxliteApi - object-oriented interface
 */
export class BoxliteApi extends BaseAPI {
    /**
     * 
     * @summary Attach to an execution via WebSocket
     * @param {string} boxId Box ID
     * @param {string} execId Execution ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public v1BoxesBoxIdExecutionsExecIdAttachGet(boxId: string, execId: string, options?: RawAxiosRequestConfig) {
        return BoxliteApiFp(this.configuration).v1BoxesBoxIdExecutionsExecIdAttachGet(boxId, execId, options).then((request) => request(this.axios, this.basePath));
    }
}

