/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite Analytics API
 * BoxLite Analytics API - Read-only telemetry and usage data. Authenticated via BoxLite API keys or JWT tokens.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ModelsSpan {
    'durationMs'?: number;
    'parentSpanId'?: string;
    'spanAttributes'?: { [key: string]: string; };
    'spanId'?: string;
    'spanName'?: string;
    'statusCode'?: string;
    'statusMessage'?: string;
    'timestamp'?: string;
    'traceId'?: string;
}

