/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite Analytics API
 * BoxLite Analytics API - Read-only telemetry and usage data. Authenticated via BoxLite API keys or JWT tokens.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ModelsBoxUsage {
    'boxId'?: string;
    'firstStart'?: string;
    'lastEnd'?: string;
    'totalCPUSeconds'?: number;
    'totalDiskGBSeconds'?: number;
    'totalGPUSeconds'?: number;
    'totalPrice'?: number;
    'totalRAMGBSeconds'?: number;
}

