/*
 * Copyright 2025 Daytona Platforms Inc.
 * Modified by BoxLite AI, 2025-2026
 * SPDX-License-Identifier: AGPL-3.0
 */

export enum JobType {
  CREATE_BOX = 'CREATE_BOX',
  START_BOX = 'START_BOX',
  STOP_BOX = 'STOP_BOX',
  DESTROY_BOX = 'DESTROY_BOX',
  RESIZE_BOX = 'RESIZE_BOX',
  CREATE_BACKUP = 'CREATE_BACKUP',
  BUILD_SNAPSHOT = 'BUILD_SNAPSHOT',
  PULL_SNAPSHOT = 'PULL_SNAPSHOT',
  RECOVER_BOX = 'RECOVER_BOX',
  INSPECT_SNAPSHOT_IN_REGISTRY = 'INSPECT_SNAPSHOT_IN_REGISTRY',
  REMOVE_SNAPSHOT = 'REMOVE_SNAPSHOT',
  UPDATE_BOX_NETWORK_SETTINGS = 'UPDATE_BOX_NETWORK_SETTINGS',
}
