/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the BoxLabels type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BoxLabels{}

// BoxLabels struct for BoxLabels
type BoxLabels struct {
	// Key-value pairs of labels
	Labels map[string]string `json:"labels"`
	AdditionalProperties map[string]interface{}
}

type _BoxLabels BoxLabels

// NewBoxLabels instantiates a new BoxLabels object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBoxLabels(labels map[string]string) *BoxLabels {
	this := BoxLabels{}
	this.Labels = labels
	return &this
}

// NewBoxLabelsWithDefaults instantiates a new BoxLabels object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBoxLabelsWithDefaults() *BoxLabels {
	this := BoxLabels{}
	return &this
}

// GetLabels returns the Labels field value
func (o *BoxLabels) GetLabels() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *BoxLabels) GetLabelsOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Labels, true
}

// SetLabels sets field value
func (o *BoxLabels) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o BoxLabels) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BoxLabels) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["labels"] = o.Labels

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BoxLabels) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"labels",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBoxLabels := _BoxLabels{}

	err = json.Unmarshal(data, &varBoxLabels)

	if err != nil {
		return err
	}

	*o = BoxLabels(varBoxLabels)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "labels")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBoxLabels struct {
	value *BoxLabels
	isSet bool
}

func (v NullableBoxLabels) Get() *BoxLabels {
	return v.value
}

func (v *NullableBoxLabels) Set(val *BoxLabels) {
	v.value = val
	v.isSet = true
}

func (v NullableBoxLabels) IsSet() bool {
	return v.isSet
}

func (v *NullableBoxLabels) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBoxLabels(val *BoxLabels) *NullableBoxLabels {
	return &NullableBoxLabels{value: val, isSet: true}
}

func (v NullableBoxLabels) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBoxLabels) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


