/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateOrganizationQuota type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOrganizationQuota{}

// UpdateOrganizationQuota struct for UpdateOrganizationQuota
type UpdateOrganizationQuota struct {
	MaxCpuPerBox NullableFloat32 `json:"maxCpuPerBox"`
	MaxMemoryPerBox NullableFloat32 `json:"maxMemoryPerBox"`
	MaxDiskPerBox NullableFloat32 `json:"maxDiskPerBox"`
	SnapshotQuota NullableFloat32 `json:"snapshotQuota"`
	MaxSnapshotSize NullableFloat32 `json:"maxSnapshotSize"`
	VolumeQuota NullableFloat32 `json:"volumeQuota"`
	AuthenticatedRateLimit NullableFloat32 `json:"authenticatedRateLimit"`
	BoxCreateRateLimit NullableFloat32 `json:"boxCreateRateLimit"`
	BoxLifecycleRateLimit NullableFloat32 `json:"boxLifecycleRateLimit"`
	AuthenticatedRateLimitTtlSeconds NullableFloat32 `json:"authenticatedRateLimitTtlSeconds"`
	BoxCreateRateLimitTtlSeconds NullableFloat32 `json:"boxCreateRateLimitTtlSeconds"`
	BoxLifecycleRateLimitTtlSeconds NullableFloat32 `json:"boxLifecycleRateLimitTtlSeconds"`
	// Time in minutes before an unused snapshot is deactivated
	SnapshotDeactivationTimeoutMinutes NullableFloat32 `json:"snapshotDeactivationTimeoutMinutes"`
	AdditionalProperties map[string]interface{}
}

type _UpdateOrganizationQuota UpdateOrganizationQuota

// NewUpdateOrganizationQuota instantiates a new UpdateOrganizationQuota object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOrganizationQuota(maxCpuPerBox NullableFloat32, maxMemoryPerBox NullableFloat32, maxDiskPerBox NullableFloat32, snapshotQuota NullableFloat32, maxSnapshotSize NullableFloat32, volumeQuota NullableFloat32, authenticatedRateLimit NullableFloat32, boxCreateRateLimit NullableFloat32, boxLifecycleRateLimit NullableFloat32, authenticatedRateLimitTtlSeconds NullableFloat32, boxCreateRateLimitTtlSeconds NullableFloat32, boxLifecycleRateLimitTtlSeconds NullableFloat32, snapshotDeactivationTimeoutMinutes NullableFloat32) *UpdateOrganizationQuota {
	this := UpdateOrganizationQuota{}
	this.MaxCpuPerBox = maxCpuPerBox
	this.MaxMemoryPerBox = maxMemoryPerBox
	this.MaxDiskPerBox = maxDiskPerBox
	this.SnapshotQuota = snapshotQuota
	this.MaxSnapshotSize = maxSnapshotSize
	this.VolumeQuota = volumeQuota
	this.AuthenticatedRateLimit = authenticatedRateLimit
	this.BoxCreateRateLimit = boxCreateRateLimit
	this.BoxLifecycleRateLimit = boxLifecycleRateLimit
	this.AuthenticatedRateLimitTtlSeconds = authenticatedRateLimitTtlSeconds
	this.BoxCreateRateLimitTtlSeconds = boxCreateRateLimitTtlSeconds
	this.BoxLifecycleRateLimitTtlSeconds = boxLifecycleRateLimitTtlSeconds
	this.SnapshotDeactivationTimeoutMinutes = snapshotDeactivationTimeoutMinutes
	return &this
}

// NewUpdateOrganizationQuotaWithDefaults instantiates a new UpdateOrganizationQuota object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOrganizationQuotaWithDefaults() *UpdateOrganizationQuota {
	this := UpdateOrganizationQuota{}
	return &this
}

// GetMaxCpuPerBox returns the MaxCpuPerBox field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *UpdateOrganizationQuota) GetMaxCpuPerBox() float32 {
	if o == nil || o.MaxCpuPerBox.Get() == nil {
		var ret float32
		return ret
	}

	return *o.MaxCpuPerBox.Get()
}

// GetMaxCpuPerBoxOk returns a tuple with the MaxCpuPerBox field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateOrganizationQuota) GetMaxCpuPerBoxOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxCpuPerBox.Get(), o.MaxCpuPerBox.IsSet()
}

// SetMaxCpuPerBox sets field value
func (o *UpdateOrganizationQuota) SetMaxCpuPerBox(v float32) {
	o.MaxCpuPerBox.Set(&v)
}

// GetMaxMemoryPerBox returns the MaxMemoryPerBox field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *UpdateOrganizationQuota) GetMaxMemoryPerBox() float32 {
	if o == nil || o.MaxMemoryPerBox.Get() == nil {
		var ret float32
		return ret
	}

	return *o.MaxMemoryPerBox.Get()
}

// GetMaxMemoryPerBoxOk returns a tuple with the MaxMemoryPerBox field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateOrganizationQuota) GetMaxMemoryPerBoxOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxMemoryPerBox.Get(), o.MaxMemoryPerBox.IsSet()
}

// SetMaxMemoryPerBox sets field value
func (o *UpdateOrganizationQuota) SetMaxMemoryPerBox(v float32) {
	o.MaxMemoryPerBox.Set(&v)
}

// GetMaxDiskPerBox returns the MaxDiskPerBox field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *UpdateOrganizationQuota) GetMaxDiskPerBox() float32 {
	if o == nil || o.MaxDiskPerBox.Get() == nil {
		var ret float32
		return ret
	}

	return *o.MaxDiskPerBox.Get()
}

// GetMaxDiskPerBoxOk returns a tuple with the MaxDiskPerBox field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateOrganizationQuota) GetMaxDiskPerBoxOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxDiskPerBox.Get(), o.MaxDiskPerBox.IsSet()
}

// SetMaxDiskPerBox sets field value
func (o *UpdateOrganizationQuota) SetMaxDiskPerBox(v float32) {
	o.MaxDiskPerBox.Set(&v)
}

// GetSnapshotQuota returns the SnapshotQuota field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *UpdateOrganizationQuota) GetSnapshotQuota() float32 {
	if o == nil || o.SnapshotQuota.Get() == nil {
		var ret float32
		return ret
	}

	return *o.SnapshotQuota.Get()
}

// GetSnapshotQuotaOk returns a tuple with the SnapshotQuota field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateOrganizationQuota) GetSnapshotQuotaOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SnapshotQuota.Get(), o.SnapshotQuota.IsSet()
}

// SetSnapshotQuota sets field value
func (o *UpdateOrganizationQuota) SetSnapshotQuota(v float32) {
	o.SnapshotQuota.Set(&v)
}

// GetMaxSnapshotSize returns the MaxSnapshotSize field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *UpdateOrganizationQuota) GetMaxSnapshotSize() float32 {
	if o == nil || o.MaxSnapshotSize.Get() == nil {
		var ret float32
		return ret
	}

	return *o.MaxSnapshotSize.Get()
}

// GetMaxSnapshotSizeOk returns a tuple with the MaxSnapshotSize field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateOrganizationQuota) GetMaxSnapshotSizeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxSnapshotSize.Get(), o.MaxSnapshotSize.IsSet()
}

// SetMaxSnapshotSize sets field value
func (o *UpdateOrganizationQuota) SetMaxSnapshotSize(v float32) {
	o.MaxSnapshotSize.Set(&v)
}

// GetVolumeQuota returns the VolumeQuota field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *UpdateOrganizationQuota) GetVolumeQuota() float32 {
	if o == nil || o.VolumeQuota.Get() == nil {
		var ret float32
		return ret
	}

	return *o.VolumeQuota.Get()
}

// GetVolumeQuotaOk returns a tuple with the VolumeQuota field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateOrganizationQuota) GetVolumeQuotaOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.VolumeQuota.Get(), o.VolumeQuota.IsSet()
}

// SetVolumeQuota sets field value
func (o *UpdateOrganizationQuota) SetVolumeQuota(v float32) {
	o.VolumeQuota.Set(&v)
}

// GetAuthenticatedRateLimit returns the AuthenticatedRateLimit field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *UpdateOrganizationQuota) GetAuthenticatedRateLimit() float32 {
	if o == nil || o.AuthenticatedRateLimit.Get() == nil {
		var ret float32
		return ret
	}

	return *o.AuthenticatedRateLimit.Get()
}

// GetAuthenticatedRateLimitOk returns a tuple with the AuthenticatedRateLimit field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateOrganizationQuota) GetAuthenticatedRateLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthenticatedRateLimit.Get(), o.AuthenticatedRateLimit.IsSet()
}

// SetAuthenticatedRateLimit sets field value
func (o *UpdateOrganizationQuota) SetAuthenticatedRateLimit(v float32) {
	o.AuthenticatedRateLimit.Set(&v)
}

// GetBoxCreateRateLimit returns the BoxCreateRateLimit field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *UpdateOrganizationQuota) GetBoxCreateRateLimit() float32 {
	if o == nil || o.BoxCreateRateLimit.Get() == nil {
		var ret float32
		return ret
	}

	return *o.BoxCreateRateLimit.Get()
}

// GetBoxCreateRateLimitOk returns a tuple with the BoxCreateRateLimit field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateOrganizationQuota) GetBoxCreateRateLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BoxCreateRateLimit.Get(), o.BoxCreateRateLimit.IsSet()
}

// SetBoxCreateRateLimit sets field value
func (o *UpdateOrganizationQuota) SetBoxCreateRateLimit(v float32) {
	o.BoxCreateRateLimit.Set(&v)
}

// GetBoxLifecycleRateLimit returns the BoxLifecycleRateLimit field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *UpdateOrganizationQuota) GetBoxLifecycleRateLimit() float32 {
	if o == nil || o.BoxLifecycleRateLimit.Get() == nil {
		var ret float32
		return ret
	}

	return *o.BoxLifecycleRateLimit.Get()
}

// GetBoxLifecycleRateLimitOk returns a tuple with the BoxLifecycleRateLimit field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateOrganizationQuota) GetBoxLifecycleRateLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BoxLifecycleRateLimit.Get(), o.BoxLifecycleRateLimit.IsSet()
}

// SetBoxLifecycleRateLimit sets field value
func (o *UpdateOrganizationQuota) SetBoxLifecycleRateLimit(v float32) {
	o.BoxLifecycleRateLimit.Set(&v)
}

// GetAuthenticatedRateLimitTtlSeconds returns the AuthenticatedRateLimitTtlSeconds field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *UpdateOrganizationQuota) GetAuthenticatedRateLimitTtlSeconds() float32 {
	if o == nil || o.AuthenticatedRateLimitTtlSeconds.Get() == nil {
		var ret float32
		return ret
	}

	return *o.AuthenticatedRateLimitTtlSeconds.Get()
}

// GetAuthenticatedRateLimitTtlSecondsOk returns a tuple with the AuthenticatedRateLimitTtlSeconds field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateOrganizationQuota) GetAuthenticatedRateLimitTtlSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AuthenticatedRateLimitTtlSeconds.Get(), o.AuthenticatedRateLimitTtlSeconds.IsSet()
}

// SetAuthenticatedRateLimitTtlSeconds sets field value
func (o *UpdateOrganizationQuota) SetAuthenticatedRateLimitTtlSeconds(v float32) {
	o.AuthenticatedRateLimitTtlSeconds.Set(&v)
}

// GetBoxCreateRateLimitTtlSeconds returns the BoxCreateRateLimitTtlSeconds field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *UpdateOrganizationQuota) GetBoxCreateRateLimitTtlSeconds() float32 {
	if o == nil || o.BoxCreateRateLimitTtlSeconds.Get() == nil {
		var ret float32
		return ret
	}

	return *o.BoxCreateRateLimitTtlSeconds.Get()
}

// GetBoxCreateRateLimitTtlSecondsOk returns a tuple with the BoxCreateRateLimitTtlSeconds field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateOrganizationQuota) GetBoxCreateRateLimitTtlSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BoxCreateRateLimitTtlSeconds.Get(), o.BoxCreateRateLimitTtlSeconds.IsSet()
}

// SetBoxCreateRateLimitTtlSeconds sets field value
func (o *UpdateOrganizationQuota) SetBoxCreateRateLimitTtlSeconds(v float32) {
	o.BoxCreateRateLimitTtlSeconds.Set(&v)
}

// GetBoxLifecycleRateLimitTtlSeconds returns the BoxLifecycleRateLimitTtlSeconds field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *UpdateOrganizationQuota) GetBoxLifecycleRateLimitTtlSeconds() float32 {
	if o == nil || o.BoxLifecycleRateLimitTtlSeconds.Get() == nil {
		var ret float32
		return ret
	}

	return *o.BoxLifecycleRateLimitTtlSeconds.Get()
}

// GetBoxLifecycleRateLimitTtlSecondsOk returns a tuple with the BoxLifecycleRateLimitTtlSeconds field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateOrganizationQuota) GetBoxLifecycleRateLimitTtlSecondsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BoxLifecycleRateLimitTtlSeconds.Get(), o.BoxLifecycleRateLimitTtlSeconds.IsSet()
}

// SetBoxLifecycleRateLimitTtlSeconds sets field value
func (o *UpdateOrganizationQuota) SetBoxLifecycleRateLimitTtlSeconds(v float32) {
	o.BoxLifecycleRateLimitTtlSeconds.Set(&v)
}

// GetSnapshotDeactivationTimeoutMinutes returns the SnapshotDeactivationTimeoutMinutes field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *UpdateOrganizationQuota) GetSnapshotDeactivationTimeoutMinutes() float32 {
	if o == nil || o.SnapshotDeactivationTimeoutMinutes.Get() == nil {
		var ret float32
		return ret
	}

	return *o.SnapshotDeactivationTimeoutMinutes.Get()
}

// GetSnapshotDeactivationTimeoutMinutesOk returns a tuple with the SnapshotDeactivationTimeoutMinutes field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateOrganizationQuota) GetSnapshotDeactivationTimeoutMinutesOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SnapshotDeactivationTimeoutMinutes.Get(), o.SnapshotDeactivationTimeoutMinutes.IsSet()
}

// SetSnapshotDeactivationTimeoutMinutes sets field value
func (o *UpdateOrganizationQuota) SetSnapshotDeactivationTimeoutMinutes(v float32) {
	o.SnapshotDeactivationTimeoutMinutes.Set(&v)
}

func (o UpdateOrganizationQuota) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOrganizationQuota) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["maxCpuPerBox"] = o.MaxCpuPerBox.Get()
	toSerialize["maxMemoryPerBox"] = o.MaxMemoryPerBox.Get()
	toSerialize["maxDiskPerBox"] = o.MaxDiskPerBox.Get()
	toSerialize["snapshotQuota"] = o.SnapshotQuota.Get()
	toSerialize["maxSnapshotSize"] = o.MaxSnapshotSize.Get()
	toSerialize["volumeQuota"] = o.VolumeQuota.Get()
	toSerialize["authenticatedRateLimit"] = o.AuthenticatedRateLimit.Get()
	toSerialize["boxCreateRateLimit"] = o.BoxCreateRateLimit.Get()
	toSerialize["boxLifecycleRateLimit"] = o.BoxLifecycleRateLimit.Get()
	toSerialize["authenticatedRateLimitTtlSeconds"] = o.AuthenticatedRateLimitTtlSeconds.Get()
	toSerialize["boxCreateRateLimitTtlSeconds"] = o.BoxCreateRateLimitTtlSeconds.Get()
	toSerialize["boxLifecycleRateLimitTtlSeconds"] = o.BoxLifecycleRateLimitTtlSeconds.Get()
	toSerialize["snapshotDeactivationTimeoutMinutes"] = o.SnapshotDeactivationTimeoutMinutes.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateOrganizationQuota) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"maxCpuPerBox",
		"maxMemoryPerBox",
		"maxDiskPerBox",
		"snapshotQuota",
		"maxSnapshotSize",
		"volumeQuota",
		"authenticatedRateLimit",
		"boxCreateRateLimit",
		"boxLifecycleRateLimit",
		"authenticatedRateLimitTtlSeconds",
		"boxCreateRateLimitTtlSeconds",
		"boxLifecycleRateLimitTtlSeconds",
		"snapshotDeactivationTimeoutMinutes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOrganizationQuota := _UpdateOrganizationQuota{}

	err = json.Unmarshal(data, &varUpdateOrganizationQuota)

	if err != nil {
		return err
	}

	*o = UpdateOrganizationQuota(varUpdateOrganizationQuota)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "maxCpuPerBox")
		delete(additionalProperties, "maxMemoryPerBox")
		delete(additionalProperties, "maxDiskPerBox")
		delete(additionalProperties, "snapshotQuota")
		delete(additionalProperties, "maxSnapshotSize")
		delete(additionalProperties, "volumeQuota")
		delete(additionalProperties, "authenticatedRateLimit")
		delete(additionalProperties, "boxCreateRateLimit")
		delete(additionalProperties, "boxLifecycleRateLimit")
		delete(additionalProperties, "authenticatedRateLimitTtlSeconds")
		delete(additionalProperties, "boxCreateRateLimitTtlSeconds")
		delete(additionalProperties, "boxLifecycleRateLimitTtlSeconds")
		delete(additionalProperties, "snapshotDeactivationTimeoutMinutes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateOrganizationQuota struct {
	value *UpdateOrganizationQuota
	isSet bool
}

func (v NullableUpdateOrganizationQuota) Get() *UpdateOrganizationQuota {
	return v.value
}

func (v *NullableUpdateOrganizationQuota) Set(val *UpdateOrganizationQuota) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOrganizationQuota) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOrganizationQuota) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOrganizationQuota(val *UpdateOrganizationQuota) *NullableUpdateOrganizationQuota {
	return &NullableUpdateOrganizationQuota{value: val, isSet: true}
}

func (v NullableUpdateOrganizationQuota) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOrganizationQuota) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


