/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the OrganizationBoxDefaultLimitedNetworkEgress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationBoxDefaultLimitedNetworkEgress{}

// OrganizationBoxDefaultLimitedNetworkEgress struct for OrganizationBoxDefaultLimitedNetworkEgress
type OrganizationBoxDefaultLimitedNetworkEgress struct {
	// Box default limited network egress
	BoxDefaultLimitedNetworkEgress bool `json:"boxDefaultLimitedNetworkEgress"`
	AdditionalProperties map[string]interface{}
}

type _OrganizationBoxDefaultLimitedNetworkEgress OrganizationBoxDefaultLimitedNetworkEgress

// NewOrganizationBoxDefaultLimitedNetworkEgress instantiates a new OrganizationBoxDefaultLimitedNetworkEgress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationBoxDefaultLimitedNetworkEgress(boxDefaultLimitedNetworkEgress bool) *OrganizationBoxDefaultLimitedNetworkEgress {
	this := OrganizationBoxDefaultLimitedNetworkEgress{}
	this.BoxDefaultLimitedNetworkEgress = boxDefaultLimitedNetworkEgress
	return &this
}

// NewOrganizationBoxDefaultLimitedNetworkEgressWithDefaults instantiates a new OrganizationBoxDefaultLimitedNetworkEgress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationBoxDefaultLimitedNetworkEgressWithDefaults() *OrganizationBoxDefaultLimitedNetworkEgress {
	this := OrganizationBoxDefaultLimitedNetworkEgress{}
	return &this
}

// GetBoxDefaultLimitedNetworkEgress returns the BoxDefaultLimitedNetworkEgress field value
func (o *OrganizationBoxDefaultLimitedNetworkEgress) GetBoxDefaultLimitedNetworkEgress() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.BoxDefaultLimitedNetworkEgress
}

// GetBoxDefaultLimitedNetworkEgressOk returns a tuple with the BoxDefaultLimitedNetworkEgress field value
// and a boolean to check if the value has been set.
func (o *OrganizationBoxDefaultLimitedNetworkEgress) GetBoxDefaultLimitedNetworkEgressOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BoxDefaultLimitedNetworkEgress, true
}

// SetBoxDefaultLimitedNetworkEgress sets field value
func (o *OrganizationBoxDefaultLimitedNetworkEgress) SetBoxDefaultLimitedNetworkEgress(v bool) {
	o.BoxDefaultLimitedNetworkEgress = v
}

func (o OrganizationBoxDefaultLimitedNetworkEgress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationBoxDefaultLimitedNetworkEgress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["boxDefaultLimitedNetworkEgress"] = o.BoxDefaultLimitedNetworkEgress

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrganizationBoxDefaultLimitedNetworkEgress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"boxDefaultLimitedNetworkEgress",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationBoxDefaultLimitedNetworkEgress := _OrganizationBoxDefaultLimitedNetworkEgress{}

	err = json.Unmarshal(data, &varOrganizationBoxDefaultLimitedNetworkEgress)

	if err != nil {
		return err
	}

	*o = OrganizationBoxDefaultLimitedNetworkEgress(varOrganizationBoxDefaultLimitedNetworkEgress)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "boxDefaultLimitedNetworkEgress")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrganizationBoxDefaultLimitedNetworkEgress struct {
	value *OrganizationBoxDefaultLimitedNetworkEgress
	isSet bool
}

func (v NullableOrganizationBoxDefaultLimitedNetworkEgress) Get() *OrganizationBoxDefaultLimitedNetworkEgress {
	return v.value
}

func (v *NullableOrganizationBoxDefaultLimitedNetworkEgress) Set(val *OrganizationBoxDefaultLimitedNetworkEgress) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationBoxDefaultLimitedNetworkEgress) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationBoxDefaultLimitedNetworkEgress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationBoxDefaultLimitedNetworkEgress(val *OrganizationBoxDefaultLimitedNetworkEgress) *NullableOrganizationBoxDefaultLimitedNetworkEgress {
	return &NullableOrganizationBoxDefaultLimitedNetworkEgress{value: val, isSet: true}
}

func (v NullableOrganizationBoxDefaultLimitedNetworkEgress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationBoxDefaultLimitedNetworkEgress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


