/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the CreateOrganizationQuota type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrganizationQuota{}

// CreateOrganizationQuota struct for CreateOrganizationQuota
type CreateOrganizationQuota struct {
	TotalCpuQuota *float32 `json:"totalCpuQuota,omitempty"`
	TotalMemoryQuota *float32 `json:"totalMemoryQuota,omitempty"`
	TotalDiskQuota *float32 `json:"totalDiskQuota,omitempty"`
	MaxCpuPerBox *float32 `json:"maxCpuPerBox,omitempty"`
	MaxMemoryPerBox *float32 `json:"maxMemoryPerBox,omitempty"`
	MaxDiskPerBox *float32 `json:"maxDiskPerBox,omitempty"`
	SnapshotQuota *float32 `json:"snapshotQuota,omitempty"`
	MaxSnapshotSize *float32 `json:"maxSnapshotSize,omitempty"`
	VolumeQuota *float32 `json:"volumeQuota,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateOrganizationQuota CreateOrganizationQuota

// NewCreateOrganizationQuota instantiates a new CreateOrganizationQuota object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrganizationQuota() *CreateOrganizationQuota {
	this := CreateOrganizationQuota{}
	return &this
}

// NewCreateOrganizationQuotaWithDefaults instantiates a new CreateOrganizationQuota object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrganizationQuotaWithDefaults() *CreateOrganizationQuota {
	this := CreateOrganizationQuota{}
	return &this
}

// GetTotalCpuQuota returns the TotalCpuQuota field value if set, zero value otherwise.
func (o *CreateOrganizationQuota) GetTotalCpuQuota() float32 {
	if o == nil || IsNil(o.TotalCpuQuota) {
		var ret float32
		return ret
	}
	return *o.TotalCpuQuota
}

// GetTotalCpuQuotaOk returns a tuple with the TotalCpuQuota field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationQuota) GetTotalCpuQuotaOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalCpuQuota) {
		return nil, false
	}
	return o.TotalCpuQuota, true
}

// HasTotalCpuQuota returns a boolean if a field has been set.
func (o *CreateOrganizationQuota) HasTotalCpuQuota() bool {
	if o != nil && !IsNil(o.TotalCpuQuota) {
		return true
	}

	return false
}

// SetTotalCpuQuota gets a reference to the given float32 and assigns it to the TotalCpuQuota field.
func (o *CreateOrganizationQuota) SetTotalCpuQuota(v float32) {
	o.TotalCpuQuota = &v
}

// GetTotalMemoryQuota returns the TotalMemoryQuota field value if set, zero value otherwise.
func (o *CreateOrganizationQuota) GetTotalMemoryQuota() float32 {
	if o == nil || IsNil(o.TotalMemoryQuota) {
		var ret float32
		return ret
	}
	return *o.TotalMemoryQuota
}

// GetTotalMemoryQuotaOk returns a tuple with the TotalMemoryQuota field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationQuota) GetTotalMemoryQuotaOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalMemoryQuota) {
		return nil, false
	}
	return o.TotalMemoryQuota, true
}

// HasTotalMemoryQuota returns a boolean if a field has been set.
func (o *CreateOrganizationQuota) HasTotalMemoryQuota() bool {
	if o != nil && !IsNil(o.TotalMemoryQuota) {
		return true
	}

	return false
}

// SetTotalMemoryQuota gets a reference to the given float32 and assigns it to the TotalMemoryQuota field.
func (o *CreateOrganizationQuota) SetTotalMemoryQuota(v float32) {
	o.TotalMemoryQuota = &v
}

// GetTotalDiskQuota returns the TotalDiskQuota field value if set, zero value otherwise.
func (o *CreateOrganizationQuota) GetTotalDiskQuota() float32 {
	if o == nil || IsNil(o.TotalDiskQuota) {
		var ret float32
		return ret
	}
	return *o.TotalDiskQuota
}

// GetTotalDiskQuotaOk returns a tuple with the TotalDiskQuota field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationQuota) GetTotalDiskQuotaOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalDiskQuota) {
		return nil, false
	}
	return o.TotalDiskQuota, true
}

// HasTotalDiskQuota returns a boolean if a field has been set.
func (o *CreateOrganizationQuota) HasTotalDiskQuota() bool {
	if o != nil && !IsNil(o.TotalDiskQuota) {
		return true
	}

	return false
}

// SetTotalDiskQuota gets a reference to the given float32 and assigns it to the TotalDiskQuota field.
func (o *CreateOrganizationQuota) SetTotalDiskQuota(v float32) {
	o.TotalDiskQuota = &v
}

// GetMaxCpuPerBox returns the MaxCpuPerBox field value if set, zero value otherwise.
func (o *CreateOrganizationQuota) GetMaxCpuPerBox() float32 {
	if o == nil || IsNil(o.MaxCpuPerBox) {
		var ret float32
		return ret
	}
	return *o.MaxCpuPerBox
}

// GetMaxCpuPerBoxOk returns a tuple with the MaxCpuPerBox field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationQuota) GetMaxCpuPerBoxOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxCpuPerBox) {
		return nil, false
	}
	return o.MaxCpuPerBox, true
}

// HasMaxCpuPerBox returns a boolean if a field has been set.
func (o *CreateOrganizationQuota) HasMaxCpuPerBox() bool {
	if o != nil && !IsNil(o.MaxCpuPerBox) {
		return true
	}

	return false
}

// SetMaxCpuPerBox gets a reference to the given float32 and assigns it to the MaxCpuPerBox field.
func (o *CreateOrganizationQuota) SetMaxCpuPerBox(v float32) {
	o.MaxCpuPerBox = &v
}

// GetMaxMemoryPerBox returns the MaxMemoryPerBox field value if set, zero value otherwise.
func (o *CreateOrganizationQuota) GetMaxMemoryPerBox() float32 {
	if o == nil || IsNil(o.MaxMemoryPerBox) {
		var ret float32
		return ret
	}
	return *o.MaxMemoryPerBox
}

// GetMaxMemoryPerBoxOk returns a tuple with the MaxMemoryPerBox field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationQuota) GetMaxMemoryPerBoxOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxMemoryPerBox) {
		return nil, false
	}
	return o.MaxMemoryPerBox, true
}

// HasMaxMemoryPerBox returns a boolean if a field has been set.
func (o *CreateOrganizationQuota) HasMaxMemoryPerBox() bool {
	if o != nil && !IsNil(o.MaxMemoryPerBox) {
		return true
	}

	return false
}

// SetMaxMemoryPerBox gets a reference to the given float32 and assigns it to the MaxMemoryPerBox field.
func (o *CreateOrganizationQuota) SetMaxMemoryPerBox(v float32) {
	o.MaxMemoryPerBox = &v
}

// GetMaxDiskPerBox returns the MaxDiskPerBox field value if set, zero value otherwise.
func (o *CreateOrganizationQuota) GetMaxDiskPerBox() float32 {
	if o == nil || IsNil(o.MaxDiskPerBox) {
		var ret float32
		return ret
	}
	return *o.MaxDiskPerBox
}

// GetMaxDiskPerBoxOk returns a tuple with the MaxDiskPerBox field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationQuota) GetMaxDiskPerBoxOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxDiskPerBox) {
		return nil, false
	}
	return o.MaxDiskPerBox, true
}

// HasMaxDiskPerBox returns a boolean if a field has been set.
func (o *CreateOrganizationQuota) HasMaxDiskPerBox() bool {
	if o != nil && !IsNil(o.MaxDiskPerBox) {
		return true
	}

	return false
}

// SetMaxDiskPerBox gets a reference to the given float32 and assigns it to the MaxDiskPerBox field.
func (o *CreateOrganizationQuota) SetMaxDiskPerBox(v float32) {
	o.MaxDiskPerBox = &v
}

// GetSnapshotQuota returns the SnapshotQuota field value if set, zero value otherwise.
func (o *CreateOrganizationQuota) GetSnapshotQuota() float32 {
	if o == nil || IsNil(o.SnapshotQuota) {
		var ret float32
		return ret
	}
	return *o.SnapshotQuota
}

// GetSnapshotQuotaOk returns a tuple with the SnapshotQuota field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationQuota) GetSnapshotQuotaOk() (*float32, bool) {
	if o == nil || IsNil(o.SnapshotQuota) {
		return nil, false
	}
	return o.SnapshotQuota, true
}

// HasSnapshotQuota returns a boolean if a field has been set.
func (o *CreateOrganizationQuota) HasSnapshotQuota() bool {
	if o != nil && !IsNil(o.SnapshotQuota) {
		return true
	}

	return false
}

// SetSnapshotQuota gets a reference to the given float32 and assigns it to the SnapshotQuota field.
func (o *CreateOrganizationQuota) SetSnapshotQuota(v float32) {
	o.SnapshotQuota = &v
}

// GetMaxSnapshotSize returns the MaxSnapshotSize field value if set, zero value otherwise.
func (o *CreateOrganizationQuota) GetMaxSnapshotSize() float32 {
	if o == nil || IsNil(o.MaxSnapshotSize) {
		var ret float32
		return ret
	}
	return *o.MaxSnapshotSize
}

// GetMaxSnapshotSizeOk returns a tuple with the MaxSnapshotSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationQuota) GetMaxSnapshotSizeOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxSnapshotSize) {
		return nil, false
	}
	return o.MaxSnapshotSize, true
}

// HasMaxSnapshotSize returns a boolean if a field has been set.
func (o *CreateOrganizationQuota) HasMaxSnapshotSize() bool {
	if o != nil && !IsNil(o.MaxSnapshotSize) {
		return true
	}

	return false
}

// SetMaxSnapshotSize gets a reference to the given float32 and assigns it to the MaxSnapshotSize field.
func (o *CreateOrganizationQuota) SetMaxSnapshotSize(v float32) {
	o.MaxSnapshotSize = &v
}

// GetVolumeQuota returns the VolumeQuota field value if set, zero value otherwise.
func (o *CreateOrganizationQuota) GetVolumeQuota() float32 {
	if o == nil || IsNil(o.VolumeQuota) {
		var ret float32
		return ret
	}
	return *o.VolumeQuota
}

// GetVolumeQuotaOk returns a tuple with the VolumeQuota field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationQuota) GetVolumeQuotaOk() (*float32, bool) {
	if o == nil || IsNil(o.VolumeQuota) {
		return nil, false
	}
	return o.VolumeQuota, true
}

// HasVolumeQuota returns a boolean if a field has been set.
func (o *CreateOrganizationQuota) HasVolumeQuota() bool {
	if o != nil && !IsNil(o.VolumeQuota) {
		return true
	}

	return false
}

// SetVolumeQuota gets a reference to the given float32 and assigns it to the VolumeQuota field.
func (o *CreateOrganizationQuota) SetVolumeQuota(v float32) {
	o.VolumeQuota = &v
}

func (o CreateOrganizationQuota) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrganizationQuota) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalCpuQuota) {
		toSerialize["totalCpuQuota"] = o.TotalCpuQuota
	}
	if !IsNil(o.TotalMemoryQuota) {
		toSerialize["totalMemoryQuota"] = o.TotalMemoryQuota
	}
	if !IsNil(o.TotalDiskQuota) {
		toSerialize["totalDiskQuota"] = o.TotalDiskQuota
	}
	if !IsNil(o.MaxCpuPerBox) {
		toSerialize["maxCpuPerBox"] = o.MaxCpuPerBox
	}
	if !IsNil(o.MaxMemoryPerBox) {
		toSerialize["maxMemoryPerBox"] = o.MaxMemoryPerBox
	}
	if !IsNil(o.MaxDiskPerBox) {
		toSerialize["maxDiskPerBox"] = o.MaxDiskPerBox
	}
	if !IsNil(o.SnapshotQuota) {
		toSerialize["snapshotQuota"] = o.SnapshotQuota
	}
	if !IsNil(o.MaxSnapshotSize) {
		toSerialize["maxSnapshotSize"] = o.MaxSnapshotSize
	}
	if !IsNil(o.VolumeQuota) {
		toSerialize["volumeQuota"] = o.VolumeQuota
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateOrganizationQuota) UnmarshalJSON(data []byte) (err error) {
	varCreateOrganizationQuota := _CreateOrganizationQuota{}

	err = json.Unmarshal(data, &varCreateOrganizationQuota)

	if err != nil {
		return err
	}

	*o = CreateOrganizationQuota(varCreateOrganizationQuota)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "totalCpuQuota")
		delete(additionalProperties, "totalMemoryQuota")
		delete(additionalProperties, "totalDiskQuota")
		delete(additionalProperties, "maxCpuPerBox")
		delete(additionalProperties, "maxMemoryPerBox")
		delete(additionalProperties, "maxDiskPerBox")
		delete(additionalProperties, "snapshotQuota")
		delete(additionalProperties, "maxSnapshotSize")
		delete(additionalProperties, "volumeQuota")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateOrganizationQuota struct {
	value *CreateOrganizationQuota
	isSet bool
}

func (v NullableCreateOrganizationQuota) Get() *CreateOrganizationQuota {
	return v.value
}

func (v *NullableCreateOrganizationQuota) Set(val *CreateOrganizationQuota) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrganizationQuota) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrganizationQuota) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrganizationQuota(val *CreateOrganizationQuota) *NullableCreateOrganizationQuota {
	return &NullableCreateOrganizationQuota{value: val, isSet: true}
}

func (v NullableCreateOrganizationQuota) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrganizationQuota) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


