/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite Analytics API
 * BoxLite Analytics API - Read-only telemetry and usage data. Authenticated via BoxLite API keys or JWT tokens.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ModelsLogEntry } from '../models';
// @ts-ignore
import type { ModelsMetricPoint } from '../models';
// @ts-ignore
import type { ModelsSpan } from '../models';
// @ts-ignore
import type { ModelsTraceSummary } from '../models';
/**
 * TelemetryApi - axios parameter creator
 */
export const TelemetryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve OTEL logs for a box within a time range
         * @summary Get box logs
         * @param {string} organizationId Organization ID
         * @param {string} boxId Box ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {string} [severity] Severity filter (comma-separated)
         * @param {string} [search] Search filter
         * @param {number} [limit] Page size
         * @param {number} [offset] Page offset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationOrganizationIdBoxBoxIdTelemetryLogsGet: async (organizationId: string, boxId: string, from: string, to: string, severity?: string, search?: string, limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdTelemetryLogsGet', 'organizationId', organizationId)
            // verify required parameter 'boxId' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdTelemetryLogsGet', 'boxId', boxId)
            // verify required parameter 'from' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdTelemetryLogsGet', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdTelemetryLogsGet', 'to', to)
            const localVarPath = `/organization/{organizationId}/box/{boxId}/telemetry/logs`
                .replace('{organizationId}', encodeURIComponent(String(organizationId)))
                .replace('{boxId}', encodeURIComponent(String(boxId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = to;
            }

            if (severity !== undefined) {
                localVarQueryParameter['severity'] = severity;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve OTEL metrics for a box within a time range
         * @summary Get box metrics
         * @param {string} organizationId Organization ID
         * @param {string} boxId Box ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {string} [metricNames] Metric names filter (comma-separated)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationOrganizationIdBoxBoxIdTelemetryMetricsGet: async (organizationId: string, boxId: string, from: string, to: string, metricNames?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdTelemetryMetricsGet', 'organizationId', organizationId)
            // verify required parameter 'boxId' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdTelemetryMetricsGet', 'boxId', boxId)
            // verify required parameter 'from' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdTelemetryMetricsGet', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdTelemetryMetricsGet', 'to', to)
            const localVarPath = `/organization/{organizationId}/box/{boxId}/telemetry/metrics`
                .replace('{organizationId}', encodeURIComponent(String(organizationId)))
                .replace('{boxId}', encodeURIComponent(String(boxId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = to;
            }

            if (metricNames !== undefined) {
                localVarQueryParameter['metricNames'] = metricNames;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve OTEL trace summaries for a box within a time range
         * @summary Get box traces
         * @param {string} organizationId Organization ID
         * @param {string} boxId Box ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {number} [limit] Page size
         * @param {number} [offset] Page offset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationOrganizationIdBoxBoxIdTelemetryTracesGet: async (organizationId: string, boxId: string, from: string, to: string, limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdTelemetryTracesGet', 'organizationId', organizationId)
            // verify required parameter 'boxId' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdTelemetryTracesGet', 'boxId', boxId)
            // verify required parameter 'from' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdTelemetryTracesGet', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdTelemetryTracesGet', 'to', to)
            const localVarPath = `/organization/{organizationId}/box/{boxId}/telemetry/traces`
                .replace('{organizationId}', encodeURIComponent(String(organizationId)))
                .replace('{boxId}', encodeURIComponent(String(boxId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = to;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve all spans for a trace
         * @summary Get trace spans
         * @param {string} organizationId Organization ID
         * @param {string} boxId Box ID
         * @param {string} traceId Trace ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationOrganizationIdBoxBoxIdTelemetryTracesTraceIdGet: async (organizationId: string, boxId: string, traceId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdTelemetryTracesTraceIdGet', 'organizationId', organizationId)
            // verify required parameter 'boxId' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdTelemetryTracesTraceIdGet', 'boxId', boxId)
            // verify required parameter 'traceId' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdTelemetryTracesTraceIdGet', 'traceId', traceId)
            const localVarPath = `/organization/{organizationId}/box/{boxId}/telemetry/traces/{traceId}`
                .replace('{organizationId}', encodeURIComponent(String(organizationId)))
                .replace('{boxId}', encodeURIComponent(String(boxId)))
                .replace('{traceId}', encodeURIComponent(String(traceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TelemetryApi - functional programming interface
 */
export const TelemetryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TelemetryApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve OTEL logs for a box within a time range
         * @summary Get box logs
         * @param {string} organizationId Organization ID
         * @param {string} boxId Box ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {string} [severity] Severity filter (comma-separated)
         * @param {string} [search] Search filter
         * @param {number} [limit] Page size
         * @param {number} [offset] Page offset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async organizationOrganizationIdBoxBoxIdTelemetryLogsGet(organizationId: string, boxId: string, from: string, to: string, severity?: string, search?: string, limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsLogEntry>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.organizationOrganizationIdBoxBoxIdTelemetryLogsGet(organizationId, boxId, from, to, severity, search, limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TelemetryApi.organizationOrganizationIdBoxBoxIdTelemetryLogsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve OTEL metrics for a box within a time range
         * @summary Get box metrics
         * @param {string} organizationId Organization ID
         * @param {string} boxId Box ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {string} [metricNames] Metric names filter (comma-separated)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async organizationOrganizationIdBoxBoxIdTelemetryMetricsGet(organizationId: string, boxId: string, from: string, to: string, metricNames?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsMetricPoint>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.organizationOrganizationIdBoxBoxIdTelemetryMetricsGet(organizationId, boxId, from, to, metricNames, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TelemetryApi.organizationOrganizationIdBoxBoxIdTelemetryMetricsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve OTEL trace summaries for a box within a time range
         * @summary Get box traces
         * @param {string} organizationId Organization ID
         * @param {string} boxId Box ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {number} [limit] Page size
         * @param {number} [offset] Page offset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async organizationOrganizationIdBoxBoxIdTelemetryTracesGet(organizationId: string, boxId: string, from: string, to: string, limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsTraceSummary>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.organizationOrganizationIdBoxBoxIdTelemetryTracesGet(organizationId, boxId, from, to, limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TelemetryApi.organizationOrganizationIdBoxBoxIdTelemetryTracesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve all spans for a trace
         * @summary Get trace spans
         * @param {string} organizationId Organization ID
         * @param {string} boxId Box ID
         * @param {string} traceId Trace ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async organizationOrganizationIdBoxBoxIdTelemetryTracesTraceIdGet(organizationId: string, boxId: string, traceId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsSpan>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.organizationOrganizationIdBoxBoxIdTelemetryTracesTraceIdGet(organizationId, boxId, traceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TelemetryApi.organizationOrganizationIdBoxBoxIdTelemetryTracesTraceIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TelemetryApi - factory interface
 */
export const TelemetryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TelemetryApiFp(configuration)
    return {
        /**
         * Retrieve OTEL logs for a box within a time range
         * @summary Get box logs
         * @param {string} organizationId Organization ID
         * @param {string} boxId Box ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {string} [severity] Severity filter (comma-separated)
         * @param {string} [search] Search filter
         * @param {number} [limit] Page size
         * @param {number} [offset] Page offset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationOrganizationIdBoxBoxIdTelemetryLogsGet(organizationId: string, boxId: string, from: string, to: string, severity?: string, search?: string, limit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<ModelsLogEntry>> {
            return localVarFp.organizationOrganizationIdBoxBoxIdTelemetryLogsGet(organizationId, boxId, from, to, severity, search, limit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve OTEL metrics for a box within a time range
         * @summary Get box metrics
         * @param {string} organizationId Organization ID
         * @param {string} boxId Box ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {string} [metricNames] Metric names filter (comma-separated)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationOrganizationIdBoxBoxIdTelemetryMetricsGet(organizationId: string, boxId: string, from: string, to: string, metricNames?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ModelsMetricPoint>> {
            return localVarFp.organizationOrganizationIdBoxBoxIdTelemetryMetricsGet(organizationId, boxId, from, to, metricNames, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve OTEL trace summaries for a box within a time range
         * @summary Get box traces
         * @param {string} organizationId Organization ID
         * @param {string} boxId Box ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {number} [limit] Page size
         * @param {number} [offset] Page offset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationOrganizationIdBoxBoxIdTelemetryTracesGet(organizationId: string, boxId: string, from: string, to: string, limit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<ModelsTraceSummary>> {
            return localVarFp.organizationOrganizationIdBoxBoxIdTelemetryTracesGet(organizationId, boxId, from, to, limit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve all spans for a trace
         * @summary Get trace spans
         * @param {string} organizationId Organization ID
         * @param {string} boxId Box ID
         * @param {string} traceId Trace ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationOrganizationIdBoxBoxIdTelemetryTracesTraceIdGet(organizationId: string, boxId: string, traceId: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ModelsSpan>> {
            return localVarFp.organizationOrganizationIdBoxBoxIdTelemetryTracesTraceIdGet(organizationId, boxId, traceId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TelemetryApi - object-oriented interface
 */
export class TelemetryApi extends BaseAPI {
    /**
     * Retrieve OTEL logs for a box within a time range
     * @summary Get box logs
     * @param {string} organizationId Organization ID
     * @param {string} boxId Box ID
     * @param {string} from Start time (RFC3339)
     * @param {string} to End time (RFC3339)
     * @param {string} [severity] Severity filter (comma-separated)
     * @param {string} [search] Search filter
     * @param {number} [limit] Page size
     * @param {number} [offset] Page offset
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public organizationOrganizationIdBoxBoxIdTelemetryLogsGet(organizationId: string, boxId: string, from: string, to: string, severity?: string, search?: string, limit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return TelemetryApiFp(this.configuration).organizationOrganizationIdBoxBoxIdTelemetryLogsGet(organizationId, boxId, from, to, severity, search, limit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve OTEL metrics for a box within a time range
     * @summary Get box metrics
     * @param {string} organizationId Organization ID
     * @param {string} boxId Box ID
     * @param {string} from Start time (RFC3339)
     * @param {string} to End time (RFC3339)
     * @param {string} [metricNames] Metric names filter (comma-separated)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public organizationOrganizationIdBoxBoxIdTelemetryMetricsGet(organizationId: string, boxId: string, from: string, to: string, metricNames?: string, options?: RawAxiosRequestConfig) {
        return TelemetryApiFp(this.configuration).organizationOrganizationIdBoxBoxIdTelemetryMetricsGet(organizationId, boxId, from, to, metricNames, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve OTEL trace summaries for a box within a time range
     * @summary Get box traces
     * @param {string} organizationId Organization ID
     * @param {string} boxId Box ID
     * @param {string} from Start time (RFC3339)
     * @param {string} to End time (RFC3339)
     * @param {number} [limit] Page size
     * @param {number} [offset] Page offset
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public organizationOrganizationIdBoxBoxIdTelemetryTracesGet(organizationId: string, boxId: string, from: string, to: string, limit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return TelemetryApiFp(this.configuration).organizationOrganizationIdBoxBoxIdTelemetryTracesGet(organizationId, boxId, from, to, limit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve all spans for a trace
     * @summary Get trace spans
     * @param {string} organizationId Organization ID
     * @param {string} boxId Box ID
     * @param {string} traceId Trace ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public organizationOrganizationIdBoxBoxIdTelemetryTracesTraceIdGet(organizationId: string, boxId: string, traceId: string, options?: RawAxiosRequestConfig) {
        return TelemetryApiFp(this.configuration).organizationOrganizationIdBoxBoxIdTelemetryTracesTraceIdGet(organizationId, boxId, traceId, options).then((request) => request(this.axios, this.basePath));
    }
}

