/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite Analytics API
 * BoxLite Analytics API - Read-only telemetry and usage data. Authenticated via BoxLite API keys or JWT tokens.
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ModelsAggregatedUsage } from '../models';
// @ts-ignore
import type { ModelsBoxUsage } from '../models';
// @ts-ignore
import type { ModelsUsageChartPoint } from '../models';
// @ts-ignore
import type { ModelsUsagePeriod } from '../models';
/**
 * UsageApi - axios parameter creator
 */
export const UsageApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve usage periods for a specific box within a time range
         * @summary Get box usage periods
         * @param {string} organizationId Organization ID
         * @param {string} boxId Box ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationOrganizationIdBoxBoxIdUsageGet: async (organizationId: string, boxId: string, from: string, to: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdUsageGet', 'organizationId', organizationId)
            // verify required parameter 'boxId' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdUsageGet', 'boxId', boxId)
            // verify required parameter 'from' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdUsageGet', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('organizationOrganizationIdBoxBoxIdUsageGet', 'to', to)
            const localVarPath = `/organization/{organizationId}/box/{boxId}/usage`
                .replace('{organizationId}', encodeURIComponent(String(organizationId)))
                .replace('{boxId}', encodeURIComponent(String(boxId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = to;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve aggregated usage for an organization within a time range
         * @summary Get aggregated usage
         * @param {string} organizationId Organization ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationOrganizationIdUsageAggregatedGet: async (organizationId: string, from: string, to: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('organizationOrganizationIdUsageAggregatedGet', 'organizationId', organizationId)
            // verify required parameter 'from' is not null or undefined
            assertParamExists('organizationOrganizationIdUsageAggregatedGet', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('organizationOrganizationIdUsageAggregatedGet', 'to', to)
            const localVarPath = `/organization/{organizationId}/usage/aggregated`
                .replace('{organizationId}', encodeURIComponent(String(organizationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = to;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve per-box usage for an organization within a time range
         * @summary Get per-box usage
         * @param {string} organizationId Organization ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationOrganizationIdUsageBoxGet: async (organizationId: string, from: string, to: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('organizationOrganizationIdUsageBoxGet', 'organizationId', organizationId)
            // verify required parameter 'from' is not null or undefined
            assertParamExists('organizationOrganizationIdUsageBoxGet', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('organizationOrganizationIdUsageBoxGet', 'to', to)
            const localVarPath = `/organization/{organizationId}/usage/box`
                .replace('{organizationId}', encodeURIComponent(String(organizationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = to;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve usage chart data points for an organization within a time range
         * @summary Get usage chart data
         * @param {string} organizationId Organization ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {string} [region] Region filter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationOrganizationIdUsageChartGet: async (organizationId: string, from: string, to: string, region?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('organizationOrganizationIdUsageChartGet', 'organizationId', organizationId)
            // verify required parameter 'from' is not null or undefined
            assertParamExists('organizationOrganizationIdUsageChartGet', 'from', from)
            // verify required parameter 'to' is not null or undefined
            assertParamExists('organizationOrganizationIdUsageChartGet', 'to', to)
            const localVarPath = `/organization/{organizationId}/usage/chart`
                .replace('{organizationId}', encodeURIComponent(String(organizationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (from !== undefined) {
                localVarQueryParameter['from'] = from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = to;
            }

            if (region !== undefined) {
                localVarQueryParameter['region'] = region;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsageApi - functional programming interface
 */
export const UsageApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsageApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve usage periods for a specific box within a time range
         * @summary Get box usage periods
         * @param {string} organizationId Organization ID
         * @param {string} boxId Box ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async organizationOrganizationIdBoxBoxIdUsageGet(organizationId: string, boxId: string, from: string, to: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsUsagePeriod>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.organizationOrganizationIdBoxBoxIdUsageGet(organizationId, boxId, from, to, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsageApi.organizationOrganizationIdBoxBoxIdUsageGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve aggregated usage for an organization within a time range
         * @summary Get aggregated usage
         * @param {string} organizationId Organization ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async organizationOrganizationIdUsageAggregatedGet(organizationId: string, from: string, to: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelsAggregatedUsage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.organizationOrganizationIdUsageAggregatedGet(organizationId, from, to, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsageApi.organizationOrganizationIdUsageAggregatedGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve per-box usage for an organization within a time range
         * @summary Get per-box usage
         * @param {string} organizationId Organization ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async organizationOrganizationIdUsageBoxGet(organizationId: string, from: string, to: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsBoxUsage>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.organizationOrganizationIdUsageBoxGet(organizationId, from, to, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsageApi.organizationOrganizationIdUsageBoxGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve usage chart data points for an organization within a time range
         * @summary Get usage chart data
         * @param {string} organizationId Organization ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {string} [region] Region filter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async organizationOrganizationIdUsageChartGet(organizationId: string, from: string, to: string, region?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ModelsUsageChartPoint>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.organizationOrganizationIdUsageChartGet(organizationId, from, to, region, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsageApi.organizationOrganizationIdUsageChartGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsageApi - factory interface
 */
export const UsageApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsageApiFp(configuration)
    return {
        /**
         * Retrieve usage periods for a specific box within a time range
         * @summary Get box usage periods
         * @param {string} organizationId Organization ID
         * @param {string} boxId Box ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationOrganizationIdBoxBoxIdUsageGet(organizationId: string, boxId: string, from: string, to: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ModelsUsagePeriod>> {
            return localVarFp.organizationOrganizationIdBoxBoxIdUsageGet(organizationId, boxId, from, to, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve aggregated usage for an organization within a time range
         * @summary Get aggregated usage
         * @param {string} organizationId Organization ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationOrganizationIdUsageAggregatedGet(organizationId: string, from: string, to: string, options?: RawAxiosRequestConfig): AxiosPromise<ModelsAggregatedUsage> {
            return localVarFp.organizationOrganizationIdUsageAggregatedGet(organizationId, from, to, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve per-box usage for an organization within a time range
         * @summary Get per-box usage
         * @param {string} organizationId Organization ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationOrganizationIdUsageBoxGet(organizationId: string, from: string, to: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ModelsBoxUsage>> {
            return localVarFp.organizationOrganizationIdUsageBoxGet(organizationId, from, to, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve usage chart data points for an organization within a time range
         * @summary Get usage chart data
         * @param {string} organizationId Organization ID
         * @param {string} from Start time (RFC3339)
         * @param {string} to End time (RFC3339)
         * @param {string} [region] Region filter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        organizationOrganizationIdUsageChartGet(organizationId: string, from: string, to: string, region?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<ModelsUsageChartPoint>> {
            return localVarFp.organizationOrganizationIdUsageChartGet(organizationId, from, to, region, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsageApi - object-oriented interface
 */
export class UsageApi extends BaseAPI {
    /**
     * Retrieve usage periods for a specific box within a time range
     * @summary Get box usage periods
     * @param {string} organizationId Organization ID
     * @param {string} boxId Box ID
     * @param {string} from Start time (RFC3339)
     * @param {string} to End time (RFC3339)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public organizationOrganizationIdBoxBoxIdUsageGet(organizationId: string, boxId: string, from: string, to: string, options?: RawAxiosRequestConfig) {
        return UsageApiFp(this.configuration).organizationOrganizationIdBoxBoxIdUsageGet(organizationId, boxId, from, to, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve aggregated usage for an organization within a time range
     * @summary Get aggregated usage
     * @param {string} organizationId Organization ID
     * @param {string} from Start time (RFC3339)
     * @param {string} to End time (RFC3339)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public organizationOrganizationIdUsageAggregatedGet(organizationId: string, from: string, to: string, options?: RawAxiosRequestConfig) {
        return UsageApiFp(this.configuration).organizationOrganizationIdUsageAggregatedGet(organizationId, from, to, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve per-box usage for an organization within a time range
     * @summary Get per-box usage
     * @param {string} organizationId Organization ID
     * @param {string} from Start time (RFC3339)
     * @param {string} to End time (RFC3339)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public organizationOrganizationIdUsageBoxGet(organizationId: string, from: string, to: string, options?: RawAxiosRequestConfig) {
        return UsageApiFp(this.configuration).organizationOrganizationIdUsageBoxGet(organizationId, from, to, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve usage chart data points for an organization within a time range
     * @summary Get usage chart data
     * @param {string} organizationId Organization ID
     * @param {string} from Start time (RFC3339)
     * @param {string} to End time (RFC3339)
     * @param {string} [region] Region filter
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public organizationOrganizationIdUsageChartGet(organizationId: string, from: string, to: string, region?: string, options?: RawAxiosRequestConfig) {
        return UsageApiFp(this.configuration).organizationOrganizationIdUsageChartGet(organizationId, from, to, region, options).then((request) => request(this.axios, this.basePath));
    }
}

